name: 'Config pages'
type: module
description: 'Allows the creation of custom configuration entities.'
package: Entity
dependencies:
  - text
configure: entity.config_pages.collection
# core: 8.x

# Information added by Drupal.org packaging script on 2018-04-02
version: '8.x-2.2'
core: '8.x'
project: 'config_pages'
datestamp: 1522657986
